:wrench: Add import/order and arrow-body-style rules
AckeeCZ/eslint-config pull request #25
Opened 2022-05-05 11:32 UTC by martinfoldyna

### Updates

- Added `import/order` rule with the following configuration
   - `"newlines-between": "always-and-inside-groups"` -> I am not really sure about this one, because it allows spaces inside the groups but when you try to `--fix` the document it puts a newline between each import. My proposal is to leave it like this and handle the new line deletion when running the `eslint --fix`
   - `groups: [
                "builtin",
                "external",
                "internal",
                ["parent", "sibling"],
                "index",
                "object",
            ],` -> the import groups will be grouped according to the array order and the `["parent", "sibling"]` allows to have the `parent` and `sibling` imports inside one group
    - [docs](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) 
 
- `"arrow-body-style": ["warn", "as-needed"]`
  - [docs](https://eslint.org/docs/rules/arrow-body-style)
- they are both only as `warn` to not destroy existing projects
- if you would like to extend the configuration of either of these rules feel free to comment and I will add it

Closes #24

2022-05-06 09:21 UTC, jstorm31 commented
>"newlines-between": "always-and-inside-groups" -> I am not really sure about this one, because it allows spaces inside the groups but when you try to --fix the document it puts a newline between each import. My proposal is to leave it like this and handle the new line deletion when running the eslint --fix

So why not `always`?

2022-05-06 11:23 UTC, jstorm31 commented
>rule the linter would give them warnings, that they cannot have a newline inside the group.
In my opinion, that's not necessary once we automate this. But let's wait for others' opinions. :)

2022-05-20 09:49 UTC, cermakjiri requested changes

2022-05-20 09:49 UTC, cermakjiri commented on index.js
> +            ],
- Let's include the `type` group `import type` too 🙏 
- I'd remove the `object` group. `import log = console.log;` is obsolete and shouldn't be used.
- I'd group `index` with `sibling` since they are on the same level from file structure. So I'm ok to have `['"parent", "sibling", "index"]` to represent relative imports.
- I'd group `["buildtin", "external"]` together. The division is maybe relevant in nodejs env. but no for us.

ok, so what about this?
```
groups: [
                ["builtin", "external"],
                "internal",
                ["parent", "sibling", "index",],
                 "type"
            ],
```

2022-05-20 12:48 UTC, martinfoldyna commented on index.js
> +            ],
Cool 👍. The only thing I will disagree on is the `type` group. I think it would be better to leave type imports within their groups. To prevent having all types in one group. What do you think?

2022-05-20 12:50 UTC, cermakjiri commented on index.js
> +            ],
Hm, yess, that makes actually sense

2022-05-20 12:51 UTC, martinfoldyna commented on index.js
> +            ],
Okay, changed ✅

2022-05-20 12:52 UTC, cermakjiri approved these changes

2022-05-20 12:53 UTC, merged